name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  workspaces: src-tauri

            - name: Build Tauri app
              working-directory: src-tauri
              run: cargo build --release

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: death-by-mpv-windows
                  path: src-tauri/target/release/bundle/msi/Death by MPV_0.1.1_x64_en-US.msi
                  if-no-files-found: warn
